default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: brainbuster_development
  username: <%= ENV.fetch("PGUSER", "root") %>
  password: <%= ENV.fetch("PGPASSWORD", "root") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

test:
  <<: *default
  database: brainbuster_test
  username: <%= ENV.fetch("PGUSER", "root") %>
  password: <%= ENV.fetch("PGPASSWORD", "root") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
