default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: brainbuster_development
  username: <%= ENV.fetch("PGUSER", "root") %>
  password: <%= ENV.fetch("PGPASSWORD", "root") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

test:
  <<: *default
  database: brainbuster_test
  username: <%= ENV.fetch("PGUSER", "root") %>
  password: <%= ENV.fetch("PGPASSWORD", "root") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: <%= ENV.fetch("PROD_DB_NAME", "brainbuster_production") %>
    username: <%= ENV.fetch("PROD_DB_USER", ENV.fetch("PGUSER", "root")) %>
    password: <%= ENV.fetch("PROD_DB_PASSWORD", ENV.fetch("PGPASSWORD", "root")) %>
    host: <%= ENV.fetch("PROD_DB_HOST", ENV.fetch("PGHOST", "localhost")) %>
    port: <%= ENV.fetch("PROD_DB_PORT", ENV.fetch("PGPORT", 5432)) %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: <%= ENV.fetch("PROD_CACHE_DB_NAME", ENV.fetch("PROD_DB_NAME", "brainbuster_production")) %>
    username: <%= ENV.fetch("PROD_DB_USER", ENV.fetch("PGUSER", "root")) %>
    password: <%= ENV.fetch("PROD_DB_PASSWORD", ENV.fetch("PGPASSWORD", "root")) %>
    host: <%= ENV.fetch("PROD_DB_HOST", ENV.fetch("PGHOST", "localhost")) %>
    port: <%= ENV.fetch("PROD_DB_PORT", ENV.fetch("PGPORT", 5432)) %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: <%= ENV.fetch("PROD_QUEUE_DB_NAME", ENV.fetch("PROD_DB_NAME", "brainbuster_production")) %>
    username: <%= ENV.fetch("PROD_DB_USER", ENV.fetch("PGUSER", "root")) %>
    password: <%= ENV.fetch("PROD_DB_PASSWORD", ENV.fetch("PGPASSWORD", "root")) %>
    host: <%= ENV.fetch("PROD_DB_HOST", ENV.fetch("PGHOST", "localhost")) %>
    port: <%= ENV.fetch("PROD_DB_PORT", ENV.fetch("PGPORT", 5432)) %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: <%= ENV.fetch("PROD_CABLE_DB_NAME", ENV.fetch("PROD_DB_NAME", "brainbuster_production")) %>
    username: <%= ENV.fetch("PROD_DB_USER", ENV.fetch("PGUSER", "root")) %>
    password: <%= ENV.fetch("PROD_DB_PASSWORD", ENV.fetch("PGPASSWORD", "root")) %>
    host: <%= ENV.fetch("PROD_DB_HOST", ENV.fetch("PGHOST", "localhost")) %>
    port: <%= ENV.fetch("PROD_DB_PORT", ENV.fetch("PGPORT", 5432)) %>
    migrations_paths: db/cable_migrate
