default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: brainbuster_development

test:
  <<: *default
  database: brainbuster_test

production:
  primary:
    <<: *default
    database: brainbuster_production
  cache:
    <<: *default
    database: brainbuster_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: brainbuster_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: brainbuster_production_cable
    migrations_paths: db/cable_migrate
